"--------------------------------------------------------------------------------\n"
"\n"
"  Function: ompt_target_start_trace\n"
"\n"
"  Type Signature:\n"
"\n"
"    bool ompt_target_start_trace\n"
"    (\n"
"      ompt_target_device_t *device, \n"
"      ompt_target_buffer_request_callback_t request, \n"
"      ompt_target_buffer_complete_callback_t complete, \n"
"      ompt_get_target_info_inquiry_t ompt_get_target_info\n"
"    )\n"
"\n"
"  Description:\n"
"\n"
"    Register a buffer request callback and a buffer complete \n"
"    callback using cuptiActivityRegisterCallbacks.\n"
"\n"
"--------------------------------------------------------------------------------\n"
"\n"
"  Function: ompt_target_set_trace_native\n"
"\n"
"  Type Signature:\n"
"\n"
"    int ompt_target_set_trace_native\n"
"    (\n"
"      ompt_target_device_t *device, \n"
"      bool enable, uint32_t flags\n"
"    )\n"
"\n"
"  Description:\n"
"\n"
"    Enable or disable collection of a specific kind of activity \n"
"    record for a context using cuptiActivityEnableContext or \n"
"    cuptiActivityDisableContext.\n"
"\n"
"--------------------------------------------------------------------------------\n"
"\n"
"  Function: ompt_target_get_time\n"
"\n"
"  Type Signature:\n"
"\n"
"    bool ompt_target_get_time\n"
"    (\n"
"      ompt_target_device_t *device, \n"
"      ompt_target_time_t *time\n"
"    )\n"
"\n"
"  Description:\n"
"\n"
"    Return the current time on the specified device context using \n"
"    cuptiDeviceGetTimestamp.\n"
"\n"
"--------------------------------------------------------------------------------\n"
"\n"
"  Function: ompt_target_advance_buffer_cursor\n"
"\n"
"  Type Signature:\n"
"\n"
"    int ompt_target_advance_buffer_cursor\n"
"    (\n"
"      ompt_target_buffer_t *buffer, \n"
"      size_t validSize, \n"
"      ompt_target_buffer_cursor_t current, \n"
"      ompt_target_buffer_cursor_t *next\n"
"    )\n"
"\n"
"  Description:\n"
"\n"
"    Return a cursor for the next record in the specified buffer \n"
"    given a cursor for the current record using cuptiActivityGetNextRecord.\n"
"\n"
"--------------------------------------------------------------------------------\n"
